# Generated by Django 5.1.7 on 2025-03-30 09:48

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('C', 'Club'), ('TT', 'Tech Team'), ('Co', 'Community'), ('O', 'Others')], default='C', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('category', models.ForeignKey(default='C', on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='events.bodycategory')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('roll_number', models.CharField(default='', max_length=20, unique=True)),
                ('department', models.CharField(choices=[('AE', 'Aerospace Engineering'), ('BB', 'Biosciences and Bioengineering'), ('ChE', 'Chemical Engineering'), ('CH', 'Chemistry'), ('CE', 'Civil Engineering'), ('CSE', 'Computer Science & Engineering'), ('ES', 'Earth Sciences'), ('EE', 'Electrical Engineering'), ('ESE', 'Energy Science and Engineering'), ('ESED', 'Environmental Science and Engineering'), ('HSS', 'Humanities & Social Science'), ('IEOR', 'Industrial Engineering & Operations Research'), ('MA', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('ME', 'Metallurgical Engineering & Materials Science'), ('PH', 'Physics'), ('IDC', 'Industrial Design Centre'), ('SOM', 'Shailesh J. Mehta School of Management'), ('Other', 'Other')], default='CE', max_length=100)),
                ('degree', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PhD', 'PhD'), ('MS', 'MS'), ('MBA', 'MBA'), ('M.Des', 'M.Des'), ('M.Sc', 'M.Sc'), ('MA', 'MA'), ('B.Des', 'B.Des'), ('B.Sc', 'B.Sc'), ('BA', 'BA'), ('Other', 'Other')], default='B.Tech', max_length=100)),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='events.body')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('venue', models.TextField(max_length=20, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('recurrence', models.TextField(choices=[('N', 'None'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=220)),
                ('recur_start', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('recur_end', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.body')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.user')),
            ],
        ),
    ]
