# Generated by Django 5.1.7 on 2025-03-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='events.bodycategory'),
        ),
        migrations.AlterField(
            model_name='bodycategory',
            name='name',
            field=models.CharField(choices=[('Club', 'Club'), ('Tech Team', 'Tech Team'), ('Community', 'Community'), ('Others', 'Others')], default='Club', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('N', 'None'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=220),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('AE', 'Aerospace Engineering'), ('BB', 'Biosciences and Bioengineering'), ('ChE', 'Chemical Engineering'), ('CH', 'Chemistry'), ('CE', 'Civil Engineering'), ('CSE', 'Computer Science & Engineering'), ('ES', 'Earth Sciences'), ('EE', 'Electrical Engineering'), ('ESE', 'Energy Science and Engineering'), ('ESED', 'Environmental Science and Engineering'), ('HSS', 'Humanities & Social Science'), ('IEOR', 'Industrial Engineering & Operations Research'), ('MA', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('MM', 'Metallurgical Engineering & Materials Science'), ('PH', 'Physics'), ('IDC', 'Industrial Design Centre'), ('SOM', 'Shailesh J. Mehta School of Management'), ('Other', 'Other')], default='CE', max_length=100),
        ),
    ]
